P-MVC-EF/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using P_MVC_EF.Models;

namespace P_MVC_EF.Controllers
{
    public class CoursesController : Controller
    {
        private DB_128040_practiceEntities db = new DB_128040_practiceEntities();

        // GET: Courses
        public ActionResult Index()
        {
            return View(db.Courses.ToList());
        }

        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

P-MVC-EF/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace P_MVC_EF.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

P-MVC-EF/Controllers/RegistrationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using P_MVC_EF.Models;

namespace P_MVC_EF.Controllers
{
    public class RegistrationsController : Controller
    {
        private DB_128040_practiceEntities db = new DB_128040_practiceEntities();

        // GET: Registrations
        public ActionResult Index()
        {
            var registrations = db.Registrations.Include(r => r.Course).Include(r => r.Student);
            return View(registrations.ToList());
        }

        // GET: Registrations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Registration registration = db.Registrations.Find(id);
            if (registration == null)
            {
                return HttpNotFound();
            }
            return View(registration);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

P-MVC-EF/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using P_MVC_EF.Models;

namespace P_MVC_EF.Controllers
{
    public class StudentsController : Controller
    {
        private DB_128040_practiceEntities db = new DB_128040_practiceEntities();

        // GET: Students
        public ActionResult Index()
        {
            return View(db.Students.ToList());
        }

        // GET: Students/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

P-MVC-EF/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>MVC Entity Framework Participation</h1>
    <p class="lead">This Participation covers basic use of MVC and the Entity Framework.</p>
    <p><a href="https://ou.edu" target="_blank" class="btn btn-primary btn-lg">Go to OU's homepage &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Students</h2>
        <p>
            This section will give a student's first name, last name, and favorite color.
        </p>
        <p> @Html.ActionLink("See More", "Index", "Students") &raquo;</p>
    </div>
    <div class="col-md-4">
        <h2>Courses</h2>
        <p>This section will give the name, term, and course code for each course in the database.</p>
        <p> @Html.ActionLink("See More", "Index", "Courses") &raquo;</p>
    </div>
    <div class="col-md-4">
        <h2>Registrations</h2>
        <p>This section displayes the registration info for students and courses. (Enrollment date, course name, and first name of the registered student)</p>
        <p> @Html.ActionLink("See More", "Index", "Registrations") &raquo;</p>
    </div>
</div>